version: '3.8'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.amorosandr.eu'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.amorosandr.eu'
    ports:
      - '8080:80'
      - '8443:443'
      - '822:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - '$JENKINS_HOME:/var/jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker    

  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - '$NGINX_HOME/jenkins-gitlab.conf:/etc/nginx/conf.d/jenkins-gitlab.conf:ro'
    ports:
      - "8080:80"      